allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@sec-ant/readable-stream@0.4.1'
  - '@simple-libs/stream-utils@1.2.0'
  - import-from-esm@2.0.0
  - index-to-position@1.1.0
  - json-with-bigint@3.5.3
  - make-asynchronous@1.0.1
  - read-package-up@11.0.0
  - read-package-up@12.0.0
  - tagged-tag@1.0.0
  - less@4.6.4
